### ISSUE TITLE
Gerer les acces de l'equipe

### ISSUE THREAD

**Issue by javaheap** [utbm-da/freelyforms#13]
Ajouter tous les membre de l'equipe a la team 2023 (attention il y a les deux groupes dans cette team)

https://github.com/orgs/utbm-da/teams/2023

**Comment by ayoubqrt** [comment]
Je ne pense pas avoir les droits pour inviter des gens

**Comment by javaheap** [comment]
J'ai mis emporairement le profil manager de l'organisation utbm-da

**Comment by ayoubqrt** [comment]
Je vois pas les groupes dans la team 2023
