### ISSUE TITLE
Move freelyforms-front to src/main/js

### ISSUE THREAD

**Issue by javaheap** [utbm-da/freelyforms#9]

**Comment by javaheap** [comment]
Pourquoi le projet js 2022 n'a pas été repris ?

**Comment by ayoubqrt** [comment]
Parce que nous en avons déjà discuté et que c'est vous qui m'avez proposé de supprimer.
Le projet JS de 2022 n'est qu'un template où ils ont rajoutés un formulaire hardcodé.
Voici le template qui à été utilisé : 
https://minimal-kit-react.vercel.app
https://github.com/minimal-ui-kit/material-kit-react

La nouvelle version du front utilise Vite comme bundler car il est plus moderne, plus simple et plus performant. Son écosystème est assez mature également.
